name: Build Layered Standard DAE

on:
  push:
    branches-ignore: [ 'temp/*' ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-ls-dae:
    name: Build Layered Standard DAE
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Generate revnumber
      run: |
        [[ $GITHUB_REF_TYPE == "tag" ]] && REVNUMBER=${GITHUB_REF:11} || REVNUMBER=${GITHUB_SHA:0:7}
        echo GITHUB_SHA:      $GITHUB_SHA
        echo GITHUB_REF_TYPE: $GITHUB_REF_TYPE
        echo GITHUB_REF:      $GITHUB_REF
        echo REVNUMBER:       $REVNUMBER
        echo "REVNUMBER=$REVNUMBER" >> $GITHUB_ENV

    - name: Create build directory
      run: |
        mkdir -p build/schema
        mkdir -p build/images

    - name: Build HTML
      uses: avattathil/asciidoctor-action@v2
      with:
        program: "asciidoctor --destination-dir=build --backend=html5 --attribute=revnumber=${{ env.REVNUMBER }} --attribute=revdate=$(date +%F) --failure-level=WARN --verbose docs/index.adoc"

    - name: Build PDF
      run: |
        docker run --rm -v $PWD:/documents/ asciidoctor/docker-asciidoctor     \
          asciidoctor-pdf                                                      \
            -r asciidoctor-mathematical                                        \
            -a source-highlighter=rouge                                         \
            -a mathematical-format=svg                                         \
            --base-dir /documents/docs                                         \
            --destination-dir /documents/build                                 \
            --failure-level WARN                                               \
            --verbose                                                          \
            --attribute=revnumber=${{ env.REVNUMBER }}                         \
            --attribute=revdate=$(date +%F)                                    \
            docs/index.adoc

    - name: Copy resources
      run: |
        cp LICENSE.txt build
        cp schema/*.xsd build/schema
        cp -r docs/images build/images
        cp -r docs/theme/ build/theme

    - name: Archive layered standard DAE
      uses: actions/upload-artifact@v6
      with:
        name: FMI-LS-DAE
        path: build/*
        if-no-files-found: error

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        destination_dir: ${{ steps.extract_branch.outputs.branch }}
        enable_jekyll: true
