name: Validate XML manifests

on:
  push:
    paths:
      - 'examples/**/*.xml'
      - 'schema/**'
  pull_request:
    paths:
      - 'examples/**/*.xml'
      - 'schema/**'

jobs:
  validate:
    name: Validate XML against XSD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate XSD manifest
        uses: phpcsstandards/xmllint-validate@v1
        with:
          pattern: schema/fmi3LayeredStandardDaeManifest.xsd
          xsd-url: https://www.w3.org/2012/04/XMLSchema.xsd

      - name: Validate XML examples
        uses: phpcsstandards/xmllint-validate@v1
        with:
          pattern: 'examples/**/*.xml'
          xsd-file: 'schema/fmi3LayeredStandardDaeManifest.xsd'
